Examples 41 to 70
Alusus/Examples pull request #6
Opened 2023-11-29 12:23 UTC by KaisHasan314

2023-12-06 08:29 UTC, sarmadka requested changes

2023-12-06 08:29 UTC, sarmadka commented on Source/ArrayRelatedOperations/find_diff_index.ar.alusus
> +دالة جد_دليل_الاختلاف(م1: سند[مـصفوفة[صـحيح]]، م2: سند[مـصفوفة[صـحيح]]): صـحيح {
ربما الأفل تسميتها `جد_موضع_الاختلاف` أو `جد_بداية_الاختلاف` كي يكون المعنى أوضح.

2023-12-06 08:29 UTC, sarmadka commented on Source/FileHandling/read_nth_line.en.alusus
> +    }
أظنك هنا تقرأ السطر الذي قبل n وليس السطر n. كذلك فإنك تضيف كل سطر إلى النص nth_line قبل إعادة تصفير النص، وهذا يسبب حجزًا وتحريرا للذاكرة بلا داعي. الأفضل تحويل هذه الحلقة إلى حلقة فقط لتجاوز الأسطر التي قبل n، ثم بعد الخروج من الحلقة تضيف حلقة while لقراءة السطر المطلوب وإضافته إلى النص المرجع.

2023-12-06 08:29 UTC, sarmadka commented on Source/Geometry/line_intersection.en.alusus
> +}
لم أفهم ما تفعله هذه الدالة. ماذا تمثل القيم a و b و c؟

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/ends_with.ar.alusus
> +	}
نحتاج أن نتأكد أن طول س أكبر أو يساوي لاحق.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/replace.en.alusus
> +	}
أرجو تعديل الإزاحات.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/split.en.alusus
> +	}
هنا أيضا نحتاج لتضبيط الإزاحات.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/starts_with.ar.alusus
> +	}
هنا أيضا نحتاج للتأكد أن طول س لا يقل عن طول سابق.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/starts_with.c
> +    }
هنا أيضا نحتاج للتأكد أننا لا نصل لنهاية str قبل انتهاء prefix.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/string_slice.c
> +    char* result = (char*)malloc(sizeof(char) * (len + 1));
هنا len غير معرف.

2023-12-06 08:29 UTC, sarmadka commented on Source/StringRelatedOperations/string_slice.js
> +    for(var i = start; i < end; i++) {
```suggestion
    for(var i = start; i <= end; i++) {
```

2023-12-06 08:29 UTC, sarmadka commented on index.json
> +        "arPrompt": "تفحص فيما إذا كان كل عناصر مصفوفة معطاة تحقق معيار معرف بدالة تعيد قيمة ثـنائية",
```suggestion
        "arPrompt": "تفحص فيما إذا كان كل عناصر مصفوفة معطاة تحقق معيارًا معرفًا بدالة تعيد قيمة ثـنائية",
```

2023-12-06 08:29 UTC, sarmadka commented on index.json
> +        "arPrompt": "تفحص فيما إذا كان أي عنصر في مصفوفة معطاة يحقق معيار معرف بدالة تعيد قيمة ثـنائية",
```suggestion
        "arPrompt": "تفحص فيما إذا كان أي عنصر في مصفوفة معطاة يحقق معيارًا معرفًا بدالة تعيد قيمة ثـنائية",
```

2023-12-08 14:46 UTC, KaisHasan314 commented on Source/Geometry/line_intersection.en.alusus
> +}
مشروح ذلك في السؤال الخاص بهذا التابع

2023-12-11 07:41 UTC, KaisHasan314 commented on Source/FileHandling/read_nth_line.en.alusus
> +    }
كلا، تتم قراءة السطر n، هنا العد يبدأ من ال 1 و هذا الطبيعي عندما نقول nth line، من أجل الملاحظة الثانية فهذا صحيح سأعدلها.

2023-12-13 06:25 UTC, sarmadka approved these changes

2023-12-13 06:25 UTC, merged